{
  "openapi":"3.0.2",
  "info": {
    "title":"Be The Hero",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/DiegoVictor/bethehero-api/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "NGO",
                "properties": {
                  "id": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": "33ceb990"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authenticates user, return a Bearer Token and ngo's id and name",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ngo": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "ngo": {
                    "id": "33ceb990",
                    "name": "Schinner and Sons"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMzY2ViOTkwIiwiaWF0IjoxNjI5MzI5NTAyLCJleHAiOjE2Mjk5MzQzMDJ9.-IRuW7HE5cMLLGKSlmu3tGau3PsVco3YahHL36F3Mdg"
                }
              }
            }
          },
          "400": {
            "description": "Your NGO was not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Your NGO was not found",
                  "code": 240,
                  "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/ngos": {
      "get": {
        "tags": ["NGOS"],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "example": 1,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lists NGOs",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/NGO"
                      },
                      {
                        "title": "NGO",
                        "properties": {
                          "incidents_url": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "id": "33ceb990",
                    "name": "Schinner and Sons",
                    "email": "diegovictorgonzaga@gmail.com",
                    "whatsapp": "39379976591",
                    "city": "Corinefurt",
                    "uf": "NE",
                    "incidents_url": "http://localhost:3333/v1/ngos/33ceb990/incidents",
                    "url": "http://localhost:3333/v1/ngos/33ceb990"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              },
              "Link": {
                "description": "Next, Previous, First and Last page's urls",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["NGOS"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "whatsapp",
                  "city",
                  "uf"
                ],
                "title": "NGO",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "whatsapp": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "uf": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Schinner and Sons",
                "email": "diegovictorgonzaga@gmail.com",
                "whatsapp": "39379976591",
                "city": "Corinefurt",
                "uf": "NE"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Create a new NGO",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "id": "33ceb990"
                }
              }
            }
          }
        }
      }
    },
    "/ngos/{id}": {
      "get": {
        "tags": ["NGOS"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "33ceb990"
          }
        ],
        "responses": {
          "200": {
            "description": "Return one NGO",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/NGO"
                    },
                    {
                      "title": "NGO",
                      "properties": {
                        "incidents_url": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "33ceb990",
                  "name": "Schinner and Sons",
                  "email": "diegovictorgonzaga@gmail.com",
                  "whatsapp": "39379976591",
                  "city": "Corinefurt",
                  "uf": "NE",
                  "incidents_url": "http://localhost:3333/v1/ngos/33ceb990/incidents",
                  "url": "http://localhost:3333/v1/ngos/33ceb990"
                }
              }
            }
          },
          "404": {
            "description": "NGO not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "NGO not found",
                  "code": 244,
                  "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
    "/ngos/{ngo_id}/incidents": {
      "get": {
        "tags": ["NGOS"],
        "parameters": [
          {
            "in": "path",
            "name": "ngo_id",
            "required": true,
            "example": "33ceb990",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "page",
            "required": false,
            "example": 1,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List NGO's incidents",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Incident"
                      },
                      {
                        "title": "Incident",
                        "properties": {
                          "ngo_id": {
                            "type": "string"
                          },
                          "ngo_url": {
                            "type": "string"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "id": 1,
                    "title": "Forward Tactics Representative",
                    "description": "Adipisci non assumenda ad sequi. Mollitia numquam voluptatum qui non nulla ad deleniti.",
                    "value": 512.93,
                    "ngo_id": "33ceb990",
                    "ngo_url": "http://localhost:3333/v1/ngos/33ceb990",
                    "url": "http://localhost:3333/v1/incidents/1"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              },
              "Link": {
                "description": "Next, Previous, First and Last page's urls",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/incidents": {
      "get": {
        "tags": ["Incidents"],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "required": false,
            "schema": {
              "type": "integer"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "List incidents",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/Incident"
                      },
                      {
                        "title": "Incident",
                        "properties": {
                          "ngo": {
                            "$ref": "#/components/schemas/NGO"
                          }
                        }
                      }
                    ]
                  }
                },
                "example": [
                  {
                    "id": 1,
                    "title": "Forward Tactics Representative",
                    "description": "Adipisci non assumenda ad sequi. Mollitia numquam voluptatum qui non nulla ad deleniti.",
                    "value": 512.93,
                    "ngo": {
                      "id": "33ceb990",
                      "name": "Schinner and Sons",
                      "email": "diegovictorgonzaga@gmail.com",
                      "whatsapp": "39379976591",
                      "city": "Corinefurt",
                      "uf": "NE",
                      "url": "http://localhost:3333/v1/ngos/33ceb990"
                    },
                    "url": "http://localhost:3333/v1/incidents/1"
                  }
                ]
              }
            },
            "headers": {
              "X-Total-Count": {
                "description": "Total number of registries in the database",
                "schema": {
                  "type": "integer"
                }
              },
              "Link": {
                "description": "Next, Previous, First and Last page's urls",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Incidents"],
        "security": [
          {
            "bearer": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "title",
                  "description",
                  "value"
                ],
                "title": "Incident",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "value": {
                    "type": "number"
                  }
                }
              },
              "example": {
                "title": "Forward Tactics Representative",
                "description": "Adipisci non assumenda ad sequi. Mollitia numquam voluptatum qui non nulla ad deleniti.",
                "value": 512.93
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create new incidents",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "title": "Incident",
                  "properties": {
                    "id": {
                      "type": "integer"
                    }
                  }
                },
                "example": {
                  "id": 1
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        }
      }
    },
    "/incidents/{id}": {
      "get": {
        "tags": ["Incidents"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Return one incident",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Incident"
                },
                "example": {
                  "id": 1,
                  "title": "Forward Tactics Representative",
                  "description": "Adipisci non assumenda ad sequi. Mollitia numquam voluptatum qui non nulla ad deleniti.",
                  "value": 512.93,
                  "ngo_id": "33ceb990",
                  "ngo_url": "http://localhost:3333/v1/ngos/33ceb990",
                  "url": "http://localhost:3333/v1/incidents/1"
                }
              }
            }
          },
          "404": {
            "description": "Incident not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Incident not found",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Incidents"],
        "security": [
          {
            "bearer": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "example": 1
          }
        ],
        "responses": {
          "204": {
            "description": "Remove an incident"
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "description": "This incident is not owned by your NGO",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "Incident":  {
                    "value": {
                      "statusCode": 401,
                      "error": "Unauthorized",
                      "message": "This incident is not owned by your NGO",
                      "attributes": {
                        "code": 141,
                        "error": "This incident is not owned by your NGO"
                      },
                      "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
                    }
                  },
                  "Authorization": {
                    "value": {
                      "statusCode": 401,
                      "error": "Unauthorized",
                      "message": "Token invalid",
                      "attributes": {
                        "code": 341,
                        "error": "Token invalid"
                      },
                      "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Incident not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 404,
                  "error": "Not Found",
                  "message": "Incident not found",
                  "code": 144,
                  "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "NGO": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "whatsapp": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "uf": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "Incident": {
        "properties": {
          "id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "value": {
            "type": "number"
          },
          "url": {
            "type": "string"
          }
        }
      },
      "Error": {
        "oneOf": [
          {
            "properties": {
              "statusCode": {
                "type": "integer"
              },
              "error": {
                "type": "string"
              },
              "message": {
                "type": "string"
              },
              "code": {
                "type": "integer"
              },
              "docs": {
                "type": "string"
              }
            }
          },
          {
            "properties": {
              "statusCode": {
                "type": "integer"
              },
              "error": {
                "type": "string"
              },
              "message": {
                "type": "string"
              },
              "attributes": {
                "type": "object",
                "properties": {
                  "code": {
                    "type": "integer"
                  },
                  "error": {
                    "type": "string"
                  }
                }
              },
              "docs": {
                "type": "string"
              }
            }
          }
        ]
      }
    },
    "responses": {
      "400": {
        "description": "Token not provided",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "example": {
              "statusCode": 400,
              "error": "Bad Request",
              "message": "Token not provided",
              "code": 340,
              "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
            }
          }
        }
      },
      "401": {
        "description": "Token invalid",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            },
            "example": {
              "statusCode": 401,
              "error": "Unauthorized",
              "message": "Token invalid",
              "attributes": {
                "code": 341,
                "error": "Token invalid"
              },
              "docs": "https://github.com/DiegoVictor/bethehero-api#errors-reference"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "scheme": "bearer",
        "type": "http"
      }
    }
  }
}
